### ISSUE TITLE
why using audio inject id=29?

### ISSUE THREAD

**Issue by shanzhuer** [tegalan/Clover-X260#1]
why using audio inject id=29?
<key>Audio</key>
		<dict>
			<key>Inject</key>
			<integer>29</integer>
		</dict>
is your chip alc298?
daliansky use audio inject id=28 for alc293

**Comment by suciptoid** [comment]
Refer to https://github.com/acidanthera/AppleALC/wiki/Supported-codecs you can use 11,28,29 for this chip.

I'm using layout id 11 for my opencore configuration, and it's also working, see: https://github.com/tegalan/opencore-x260/blob/master/EFI/OC/config.plist#L542

My chip 293
